# =============================================================================
# ESP Audio Stack microphone gain control
# =============================================================================

substitutions:
  mic_gain_min: "-20"
  mic_gain_max: "30"

number:
  - platform: esp_audio_stack
    esp_audio_stack_id: audio_stack
    mic_gain:
      id: mic_gain
      name: Mic Gain
      min_value: ${mic_gain_min}
      max_value: ${mic_gain_max}
